apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sergio-tips
  name: sergio-tips
  namespace: sergio-dev
spec:
  containers:
  - image: nginx
    name: sergio-tips
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
