apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sergio-pod
  name: sergio-pod
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /sergio-app
      name: primeiro-emptydir
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"  
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
